url: "https://hato1198.github.io"
baseurl: "/mouse-cursor-checker"

plugins:
  - jekyll-sitemap

exclude:
  - google7aa94270c7800c73.html

sitemap:
  hostname: "https://hato1198.github.io"

timezone: "Asia/Tokyo"
